### ISSUE TITLE
save_block error

### ISSUE THREAD

**Issue by mumu714** [HarukaMa/aleo-explorer#17]
Traceback (most recent call last):
  File "/home/ps/aleo-explorer-python/aleo-explorer/node/node.py", line 80, in worker
    await self.parse_message(Frame.load(BytesIO(frame)))
  File "/home/ps/aleo-explorer-python/aleo-explorer/node/node.py", line 105, in parse_message
    await self.explorer_request(explorer.Request.ProcessBlock(block))
  File "/home/ps/aleo-explorer-python/aleo-explorer/explorer/explorer.py", line 48, in node_request
    await self.add_block(request.block)
  File "/home/ps/aleo-explorer-python/aleo-explorer/explorer/explorer.py", line 130, in add_block
    await self.db.save_block(block)
  File "/home/ps/aleo-explorer-python/aleo-explorer/db.py", line 1304, in save_block
    await self._save_block(block)
  File "/home/ps/aleo-explorer-python/aleo-explorer/db.py", line 27, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/db.py", line 891, in _save_block
    block_reward += await block.get_total_priority_fee(self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_block.py", line 3449, in get_total_priority_fee
    return sum([(await t.get_fee_breakdown(db)).priority_fee for t in self.transactions])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_block.py", line 3449, in <listcomp>
    return sum([(await t.get_fee_breakdown(db)).priority_fee for t in self.transactions])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_block.py", line 2610, in get_fee_breakdown
    finalize_costs = await execution.finalize_costs(db)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_block.py", line 2401, in finalize_costs
    program = await get_program(db, str(transition.program_id))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/util/global_cache.py", line 16, in get_program
    program = Program.load(BytesIO(program))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_block.py", line 885, in load
    i = Struct.load(data)
        ^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_block.py", line 151, in load
    members = Vec[Tuple[Identifier, PlaintextType], u16].load(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/generic.py", line 135, in load
    return cls(list(value_type.load(data) for _ in range(size)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/generic.py", line 135, in <genexpr>
    return cls(list(value_type.load(data) for _ in range(size)))
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/generic.py", line 100, in load
    value.append(t.load(data))
                 ^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_instruction.py", line 684, in load
    return ArrayPlaintextType.load(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_instruction.py", line 785, in load
    array_type = ArrayType.load(data)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_instruction.py", line 750, in load
    plaintext_type = PlaintextType.load(data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_instruction.py", line 684, in load
    return ArrayPlaintextType.load(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_instruction.py", line 785, in load
    array_type = ArrayType.load(data)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_instruction.py", line 750, in load
    plaintext_type = PlaintextType.load(data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/vm_instruction.py", line 678, in load
    type_ = cls.Type.load(data)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/ps/aleo-explorer-python/aleo-explorer/aleo_types/basic.py", line 217, in load
    self = cls(struct.unpack("<B", data.read(1))[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 32 is not a valid PlaintextType.Type

**Comment by HarukaMa** [comment]
It was caused by this: https://github.com/HarukaMa/aleo-explorer/commit/5cc143ab2e2d81c79f2f6af7c2a7e3449a40d97f

to manually fix, you will need to either resync or manually fix the affected program in database (load the aleo program code with aleo_explorer_rust.parse_program and save the byte code to the database)

**Comment by lkgnd671** [comment]
aleo_explorer_rust.parse_program

**Comment by lkgnd671** [comment]
aleo1pnkqhvlqjrjgf6agwzk2m9akweq5ng36kzywdlx7lel86s8vnuyqy4ugjv

what is problem ???

**Comment by HarukaMa** [comment]
> aleo1pnkqhvlqjrjgf6agwzk2m9akweq5ng36kzywdlx7lel86s8vnuyqy4ugjv
> 
> what is problem ???

I don't know. github issues is not for this.
